### PR TITLE
Rise `th2_component` metric with box name as `name` label value

### PR DESCRIPTION
**Pull request by Nikita-Smirnov-Exactpro**

### CODE REVIEW

**Comment by OptimumCode** [comment]
Are you sure that you based this PR on the right branch? I see comments that are not related to this PR

**Comment by Nikita-Smirnov-Exactpro** [comment]
> Are you sure that you based this PR on the right branch? I see comments that are not related to this PR

Corrected, thank you

**Comment by OptimumCode** [comment]
> Corrected, thank you

What is corrected? There are still commits that do not belong to this change. I think the only way to fix this is to rebase this branch based on the current master state (and drop all the duplicated commits)

**Review by OptimumCode — APPROVED** [review]
If you want you can merge it as is. But I think that we need to fix commit history first

**Comment by Nikita-Smirnov-Exactpro** [comment]
> If you want you can merge it as is. But I think that we need to fix commit history first

I'm going to use squash and merge

**Pull request merged**
