### PR TITLE
[th2-2689] adaptation to book/page cradleapi

### PR DESCRIPTION
**Pull request by andreydrobynin**

### CODE REVIEW

**Comment by andreydrobynin** [comment]
Related to [store-common PR 12](https://github.com/th2-net/th2-store-common/pull/12)

**Comment by andreydrobynin** [comment]
https://github.com/th2-net/th2-store-common/pull/12

**Review by Nikita-Smirnov-Exactpro — APPROVED** [review]

**Review by Nikita-Smirnov-Exactpro — CHANGES_REQUESTED** [review]
Let's create a common branch related to book page changes and increase the version in its.

**Comment by andreydrobynin** [comment]
> Let's create a common branch related to book page changes and increase the version in its.

@Nikita-Smirnov-Exactpro I created a new branch `th2-2150-books-pages` from last master and use it in this PR. Also I added 4.0.0 version to README and properties.
Can I merge it to `th2-2150-books-pages`?

**Review by Nikita-Smirnov-Exactpro — APPROVED** [review]

**Pull request merged**
